# Generated by Django 5.0.3 on 2025-04-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq_schedule", "0014_use_autofields_for_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bookable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="bookable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
