# Generated by Django 2.2.7 on 2020-02-08 00:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_squashed_0017_auto_20200208_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='start_end_times',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
