# Generated by Django 2.2.7 on 2020-02-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200208_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_key',
            field=models.IntegerField(default=0),
        ),
    ]
