# Generated by Django 2.2.7 on 2020-02-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order_key',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
