# Generated by Django 2.2.7 on 2020-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_queue_active_override_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='course',
            name='searchable_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'department', 'year', 'semester'), name='unique_course_name'),
        ),
    ]
