# Generated by Django 2.2.7 on 2020-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_video_chat_enabled'),
    ]

    def set_user_key_name(apps, schema_editor):
        User = apps.get_model('api', 'User')
        for user in User.objects.all().iterator():
            user.user_key = user.email.split("@")[0]
            user.save()

    def reverse_set_user_key_name(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.CharField(default='', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(set_user_key_name, reverse_set_user_key_name),
    ]
