# Generated by Django 2.2.7 on 2020-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
