# Generated by Django 2.2.7 on 2020-01-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
