# Generated by Django 2.2.7 on 2019-12-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
