# Generated by Django 2.2.7 on 2020-01-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_queue_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='email',
            field=models.EmailField(default='stevenbursztyn@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
