# Generated by Django 2.2.7 on 2020-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200109_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invite_only',
            field=models.BooleanField(default=False),
        ),
    ]
