# Generated by Django 2.2.7 on 2020-02-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='course',
            field=models.ForeignKey(default='69c95810-07bf-4f75-9ef2-9a62de1c90d0', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_questions', to='api.Course'),
            preserve_default=False,
        ),
    ]
