# Generated by Django 2.2.7 on 2020-02-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedbackquestion_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='question',
            name='rejected_reason_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='question_text',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
