# Generated by Django 2.2.7 on 2020-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_invite_only'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseuser',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_user'),
        ),
    ]
