# Generated by Django 2.2.7 on 2020-02-01 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200201_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_archived',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='feedbackquestion',
            old_name='is_active',
            new_name='archived',
        ),
        migrations.AlterField(
            model_name='radiobuttonfeedbackquestion',
            name='answer_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='sliderfeedbackquestion',
            name='answer_lower_bound',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='sliderfeedbackquestion',
            name='answer_upper_bound',
            field=models.IntegerField(editable=False),
        ),
    ]
