# Generated by Django 2.2.7 on 2020-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200201_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackquestion',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
