# Generated by Django 2.2.7 on 2020-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200201_2106'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_name',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'department', 'year', 'semester'), name='unique_course_name'),
        ),
    ]
