# Generated by Django 2.2.7 on 2020-02-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200202_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answers', to='api.FeedbackQuestion'),
        ),
    ]
