# Generated by Django 2.2.7 on 2020-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200222_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='searchable_name',
            field=models.CharField(editable=False, max_length=72),
        ),
    ]
