# Generated by Django 2.2.7 on 2020-02-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200203_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiobuttonfeedbackanswer',
            name='feedbackquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='shortanswerfeedbackanswer',
            name='feedbackquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='sliderfeedbackanswer',
            name='feedbackquestion_ptr',
        ),
        migrations.AddField(
            model_name='radiobuttonfeedbackanswer',
            name='feedbackanswer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.FeedbackAnswer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortanswerfeedbackanswer',
            name='feedbackanswer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.FeedbackAnswer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderfeedbackanswer',
            name='feedbackanswer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.FeedbackAnswer'),
            preserve_default=False,
        ),
    ]
