# Generated by Django 2.2.7 on 2020-03-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_searchable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='require_video_chat_url_on_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='video_chat_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
