# Generated by Django 2.2.7 on 2020-02-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_feedbackquestion_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_users', to='api.User'),
        ),
    ]
