# Generated by Django 2.2.7 on 2020-02-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_courseuser_invited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseuser',
            old_name='is_deactivated',
            new_name='deactivated',
        ),
    ]
