# Generated by Django 2.2.7 on 2020-02-06 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200205_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackquestion',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='radiobuttonfeedbackquestion',
            name='answer_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='sliderfeedbackquestion',
            name='answer_lower_bound',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sliderfeedbackquestion',
            name='answer_upper_bound',
            field=models.IntegerField(),
        ),
    ]
