# Generated by Django 2.2.7 on 2020-03-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_user_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authuser',
            constraint=models.UniqueConstraint(fields=('firebase_uid',), name='unique_auth_user_firebase_uid'),
        ),
        migrations.AddConstraint(
            model_name='authuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_auth_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_key',), name='unique_user_user_key'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
    ]
