# Generated by Django 2.2.7 on 2020-03-18 04:00

from django.db import migrations, models
from ohq.apps.api.util import generate_random_pretty_id

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200317_0440'),
    ]

    def set_course_pretty_id(apps, schema_editor):
        Course = apps.get_model('api', 'Course')
        for course in Course.objects.all().iterator():
            course.pretty_id = generate_random_pretty_id()
            course.save()

    def reverse_set_course_pretty_id(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='course',
            name='pretty_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.RunPython(set_course_pretty_id, reverse_set_course_pretty_id),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('pretty_id',), name='unique_course_pretty_id'),
        ),
    ]
