# Generated by Django 2.2.7 on 2020-03-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200318_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
