# Generated by Django 2.2.7 on 2020-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='should_send_up_soon_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
