# Generated by Django 2.2.7 on 2020-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200319_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_verification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
