# Generated by Django 2.2.7 on 2020-03-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200319_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sms_verified',
            field=models.NullBooleanField(),
        ),
    ]
