# Generated by Django 2.2.7 on 2020-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200319_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
