# Generated by Django 3.1 on 2020-08-16 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ohq", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="time_answered", new_name="time_responded_to",
        ),
        migrations.RemoveField(model_name="question", name="answered_by",),
        migrations.RemoveField(model_name="question", name="rejected_by",),
        migrations.RemoveField(model_name="question", name="rejected_reason_other",),
        migrations.RemoveField(model_name="question", name="time_last_updated",),
        migrations.RemoveField(model_name="question", name="time_rejected",),
        migrations.RemoveField(model_name="question", name="time_started",),
        migrations.RemoveField(model_name="question", name="time_withdrawn",),
        migrations.AddField(
            model_name="question",
            name="responded_to_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASKED", "Asked"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("ACTIVE", "Active"),
                    ("REJECTED", "Rejected"),
                    ("ANSWERED", "Answered"),
                ],
                default="ACTIVE",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="time_response_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="asked_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asked_questions",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="rejected_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
