# Generated by Django 3.1 on 2020-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0003_auto_20200822_1116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue", name="estimated_wait_time", field=models.IntegerField(default=-1),
        ),
    ]
