# Generated by Django 3.1.1 on 2020-10-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0004_auto_20200825_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ohq.course"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question", name="tags", field=models.ManyToManyField(to="ohq.Tag"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(fields=("name", "course"), name="unique_course_tag"),
        ),
    ]
