# Generated by Django 3.1.2 on 2020-12-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0004_auto_20200825_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueStatistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("AVG_WAIT", "Average wait-time"),
                            ("NUM_ANSWERED", "Number of questions answered per week"),
                            ("STUDENT_HELPED", "Students helped per week"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[("MONDAY_0_4", "Monday 12AM - 4AM")],
                        max_length=256,
                        null=True,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "queue",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ohq.queue"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="queuestatistics",
            constraint=models.UniqueConstraint(
                fields=("queue", "metric", "classification", "date"), name="unique_statistic"
            ),
        ),
    ]
