# Generated by Django 3.1.2 on 2020-12-26 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0004_auto_20200825_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("HEATMAP_AVG_WAIT", "Average wait-time heatmap"),
                            ("AVG_WAIT", "Average wait-time"),
                            ("NUM_ANSWERED", "Number of questions answered per week"),
                            ("STUDENTS_HELPED", "Students helped per week"),
                            ("AVG_TIME_HELPING", "Average time helping students"),
                            ("LIST_WAIT_TIME_DAYS", "List of wait times per day"),
                        ],
                        max_length=256,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "time_range",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "12AM-4AM"),
                            (4, "4AM-8AM"),
                            (8, "8AM-12PM"),
                            (12, "12PM-4PM"),
                            (16, "4PM-8PM"),
                            (20, "8PM-12AM"),
                        ],
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "queue",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ohq.queue"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="queuestatistic",
            constraint=models.UniqueConstraint(
                fields=("queue", "metric", "day", "time_range", "date"), name="unique_statistic"
            ),
        ),
    ]
