# Generated by Django 3.1.1 on 2020-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0004_auto_20200825_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolved_note",
            field=models.BooleanField(default=True),
        ),
    ]
