# Generated by Django 3.1.1 on 2021-01-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0005_auto_20201016_1702"),
        ("ohq", "0005_auto_20201016_1459"),
    ]

    operations = []
