# Generated by Django 3.1.1 on 2020-10-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0005_auto_20201009_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ohq.Tag'),
        ),
    ]
