# Generated by Django 3.1.2 on 2020-12-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0005_auto_20201221_2055"),
    ]

    operations = [
        migrations.RenameModel(old_name="QueueStatistics", new_name="QueueStatistic",),
    ]
