# Generated by Django 3.1.2 on 2020-12-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0006_auto_20201223_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuestatistic", name="date", field=models.DateField(blank=True, null=True),
        ),
    ]
