# Generated by Django 3.1.2 on 2020-12-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0007_auto_20201224_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuestatistic",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[("MONDAY_0_4", "Monday 12AM - 4AM"), ("MONDAY_4_8", "Monday 4AM - 8AM")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queuestatistic",
            name="metric",
            field=models.CharField(
                choices=[
                    ("HEATMAP_AVG_WAIT", "Average wait-time heatmap"),
                    ("AVG_WAIT", "Average wait-time"),
                    ("NUM_ANSWERED", "Number of questions answered per week"),
                    ("STUDENTS_HELPED", "Students helped per week"),
                    ("AVG_TIME_HELPING", "Average time helping students"),
                    ("LIST_WAIT_TIME_DAYS", "List of wait times per day"),
                ],
                max_length=256,
            ),
        ),
    ]
