# Generated by Django 3.1.1 on 2021-01-25 01:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0008_auto_20210119_2218"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("HEATMAP_AVG_WAIT", "Average wait-time heatmap"),
                            ("HEATMAP_QUESTIONS_PER_TA", "Questions per TA heatmap"),
                            ("AVG_WAIT", "Average wait-time"),
                            ("NUM_ANSWERED", "Number of questions answered per week"),
                            ("STUDENTS_HELPED", "Students helped per week"),
                            ("AVG_TIME_HELPING", "Average time helping students"),
                            ("LIST_WAIT_TIME_DAYS", "List of wait times per day"),
                        ],
                        max_length=256,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "queue",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ohq.queue"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="queuestatistic",
            constraint=models.UniqueConstraint(
                fields=("queue", "metric", "day", "hour", "date"), name="unique_statistic"
            ),
        ),
    ]
