# Generated by Django 3.1.2 on 2020-12-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0008_auto_20201225_2123"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="queuestatistic", name="unique_statistic",),
        migrations.RemoveField(model_name="queuestatistic", name="classification",),
        migrations.AddField(
            model_name="queuestatistic",
            name="day",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Sunday"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="queuestatistic",
            name="time_range",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "12AM-4AM"),
                    (4, "4AM-8AM"),
                    (8, "8AM-12PM"),
                    (12, "12PM-4PM"),
                    (16, "4PM-8PM"),
                    (20, "8PM-12AM"),
                ],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="queuestatistic",
            constraint=models.UniqueConstraint(
                fields=("queue", "metric", "day", "time_range", "date"), name="unique_statistic"
            ),
        ),
    ]
