# Generated by Django 3.1.2 on 2020-12-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0009_auto_20201226_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuestatistic",
            name="day",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                null=True,
            ),
        ),
    ]
