# Generated by Django 3.1.7 on 2021-04-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0010_auto_20210407_0145"),
        ("ohq", "0010_auto_20210405_1720"),
    ]

    operations = []
