# Generated by Django 3.1.7 on 2021-04-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0010_auto_20210407_0145"),
        ("ohq", "0010_auto_20210331_2111"),
    ]

    operations = []
