# Generated by Django 3.1.7 on 2021-03-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0010_auto_20210327_2144'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipstatistic',
            name='membership_statistic',
        ),
        migrations.AddField(
            model_name='membershipstatistic',
            name='course',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='ohq.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipstatistic',
            name='metric',
            field=models.CharField(choices=[('STUDENT_AVG_TIME_HELPED', 'Student: Average time being helped'), ('STUDENT_AVG_TIME_WAITING', 'Student: Average time waiting for help'), ('INSTR_AVG_TIME_HELPING', 'Instructor: Average time helping per question'), ('INSTR_AVG_STUDENTS_PER_HOUR', 'Instructor: Average number of students helped per hour')], max_length=256),
        ),
        migrations.AddConstraint(
            model_name='membershipstatistic',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'metric'), name='membership_statistic'),
        ),
    ]
