# Generated by Django 3.1.7 on 2021-04-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0011_merge_20210415_2054"),
        ("ohq", "0011_merge_20210415_2110"),
    ]

    operations = []
