# Generated by Django 3.1.7 on 2021-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0011_merge_20210415_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='require_video_chat_url_on_questions',
            field=models.BooleanField(default=False),
        ),
    ]
