# Generated by Django 3.1.7 on 2021-03-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0011_auto_20210330_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipstatistic',
            name='course',
        ),
    ]
