# Generated by Django 3.1.7 on 2021-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0012_remove_membershipstatistic_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipstatistic',
            name='membership_statistic',
        ),
        migrations.AddConstraint(
            model_name='membershipstatistic',
            constraint=models.UniqueConstraint(fields=('user', 'metric'), name='membership_statistic'),
        ),
    ]
