# Generated by Django 3.1.7 on 2021-09-17 14:25

from django.db import migrations


def populate_require_url_in_queue(apps, schema_editor):
    Queue = apps.get_model("ohq", "Queue")
    for queue in Queue.objects.all():
        queue.require_video_chat_url_on_questions = queue.course.require_video_chat_url_on_questions
        queue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0011_merge_20210415_2110"),
    ]

    operations = [
        migrations.RunPython(populate_require_url_in_queue),
    ]
