# Generated by Django 3.1.7 on 2021-03-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0013_auto_20210330_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipStatistic',
        ),
    ]
