# Generated by Django 3.1.7 on 2021-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0015_question_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue", name="pin_enabled", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queue",
            name="pin",
            field=models.CharField(blank=True, default="", max_length=5, null=True),
        ),
    ]
