# Generated by Django 3.1.7 on 2022-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0017_auto_20211031_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="course_title", field=models.CharField(max_length=100),
        ),
    ]
