# Generated by Django 3.1.7 on 2021-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0017_auto_20211031_1615"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="timer_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
