# Generated by Django 5.0.3 on 2025-04-15 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0018_auto_20220125_0344"),
        ("ohq_schedule", "0016_alter_calendarrelation_content_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="question_timer_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queue",
            name="question_timer_start_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("STUDENT_QUESTIONS_ASKED", "Student: Questions asked"),
                            ("STUDENT_TIME_BEING_HELPED", "Student: Time being helped"),
                            ("INSTR_QUESTIONS_ANSWERED", "Instructor: Questions answered"),
                            ("INSTR_TIME_ANSWERING", "Instructor: Time answering questions"),
                        ],
                        max_length=256,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ohq.course"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("TOTAL_QUESTIONS_ASKED", "Total questions asked"),
                            ("TOTAL_QUESTIONS_ANSWERED", "Total questions answered"),
                            ("TOTAL_TIME_BEING_HELPED", "Total time being helped"),
                            ("TOTAL_TIME_HELPING", "Total time helping"),
                            ("TOTAL_STUDENTS_HELPED", "Total students helped"),
                        ],
                        max_length=256,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start", models.DateTimeField(db_index=True, verbose_name="start")),
                ("end", models.DateTimeField(db_index=True, verbose_name="end")),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="ohq_schedule.occurrence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "ordering": ["start"],
                "index_together": {("start", "end")},
            },
        ),
        migrations.AddConstraint(
            model_name="coursestatistic",
            constraint=models.UniqueConstraint(
                fields=("user", "course", "metric", "date"), name="course_statistic"
            ),
        ),
        migrations.AddConstraint(
            model_name="userstatistic",
            constraint=models.UniqueConstraint(
                fields=("user", "metric"), name="unique_user_statistic"
            ),
        ),
    ]
