# Generated by Django 3.1.7 on 2022-04-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ohq", "0019_auto_20211114_1800"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("STUDENT_AVG_TIME_HELPED", "Student: Average time being helped"),
                            ("STUDENT_AVG_TIME_WAITING", "Student: Average time waiting for help"),
                            (
                                "INSTR_AVG_TIME_HELPING",
                                "Instructor: Average time helping per question",
                            ),
                            ("STUDENT_TOTAL_TIME_HELPED", "Student: Total time being helped"),
                            ("STUDENT_TOTAL_TIME_WAITING", "Student: Total time waiting in queue"),
                            ("STUDENT_TOTAL_QUESTIONS", "Student: Total questions answered"),
                            ("INSTR_TOTAL_TIME_HELPING", "Instructor: Total time helping"),
                            ("INSTR_TOTAL_QUESTONS", "Instructor: Total questions answered"),
                        ],
                        max_length=256,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ohq.course"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="membershipstatistic",
            constraint=models.UniqueConstraint(
                fields=("user", "course", "metric"), name="membership_statistic"
            ),
        ),
    ]
