# Generated by Django 3.2.4 on 2024-03-17 04:03

from django.db import migrations, models
import ohq.models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0019_auto_20211114_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, upload_to=ohq.models.Question.get_course_upload_path),
        ),
    ]
