# Generated by Django 3.1.7 on 2024-03-26 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ohq", "0019_auto_20211114_1800"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("TOTAL_QUESTIONS_ASKED", "Total questions asked"),
                            ("TOTAL_QUESTIONS_ANSWERED", "Total questions answered"),
                            ("TOTAL_TIME_BEING_HELPED", "Total time being helped"),
                            ("TOTAL_TIME_HELPING", "Total time helping"),
                            ("TOTAL_STUDENTS_HELPED", "Total students helped"),
                        ],
                        max_length=256,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=16)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userstatistic",
            constraint=models.UniqueConstraint(
                fields=("user", "metric"), name="unique_user_statistic"
            ),
        ),
    ]
