# Generated by Django 3.2.4 on 2023-10-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0019_auto_20211114_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_prompt', models.TextField(default='\n                                  llm prompt\n                                  ')),
                ('temperature', models.DecimalField(decimal_places=5, default=0.3, max_digits=5)),
                ('model_name', models.CharField(default='gpt-3.5-turbo-16k', max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='ohq.course')),
            ],
        ),
    ]
