# Generated by Django 3.2.4 on 2023-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0020_llmitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmitems',
            name='llm_prompt',
            field=models.TextField(default=' \n        llm prompt \n        '),
        ),
        migrations.AlterField(
            model_name='llmitems',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=5),
        ),
    ]
