# Generated by Django 5.0.3 on 2024-11-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0021_queue_question_timer_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "ONE"), (2, "TWO"), (3, "THREE"), (4, "FOUR"), (5, "FIVE")]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="review",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ohq.review"
            ),
        ),
    ]
