# Generated by Django 3.2.4 on 2023-10-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0021_auto_20231005_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='llm_response',
            field=models.TextField(blank=True),
        ),
    ]
