# Generated by Django 3.1.7 on 2022-11-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0021_auto_20221110_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohq.review'),
        ),
    ]
