# Generated by Django 5.0.3 on 2025-04-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0021_occurrence"),
        ("ohq", "0021_queue_question_timer_enabled_and_more"),
    ]

    operations = []
