# Generated by Django 5.0.3 on 2024-11-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0022_review_question_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="reviews",
            field=models.BooleanField(default=True),
        ),
    ]
