# Generated by Django 5.0.3 on 2024-10-18 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0022_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end",
            field=models.DateTimeField(blank=True, db_index=True, verbose_name="end"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start",
            field=models.DateTimeField(blank=True, db_index=True, verbose_name="start"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("occurrence", "user"), name="unique_reservation"
            ),
        ),
    ]
