# Generated by Django 3.2.4 on 2023-10-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0022_question_llm_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LlmItems',
            new_name='LlmSetting',
        ),
    ]
