# Generated by Django 3.2.4 on 2023-10-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0023_rename_llmitems_llmsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsetting',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='ohq.course'),
        ),
        migrations.AlterField(
            model_name='llmsetting',
            name='llm_prompt',
            field=models.TextField(default=' \n        \\PINECONE CONTEXT\\\n        llm prompt \n        '),
        ),
    ]
