# Generated by Django 5.0.3 on 2024-10-18 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0023_alter_booking_end_alter_booking_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["start"],
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_reservation",
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("occurrence", "user")},
        ),
        migrations.AlterIndexTogether(
            name="booking",
            index_together={("start", "end")},
        ),
    ]
