# Generated by Django 5.0.3 on 2024-11-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0024_rename_reviews_course_allow_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ohq.question",
            ),
        ),
    ]
