# Generated by Django 5.0.3 on 2024-10-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0024_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
