# Generated by Django 3.2.4 on 2023-10-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0025_alter_llmsetting_llm_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmsetting',
            name='llm_prompt',
        ),
    ]
