# Generated by Django 5.0.3 on 2025-01-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0021_queue_question_timer_enabled_and_more"),
        ("ohq", "0025_alter_booking_unique_together"),
    ]

    operations = []
