# Generated by Django 5.0.3 on 2025-03-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohq", "0026_merge_20250126_1914"),
        ("schedule", "0016_occurrence_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="schedule.occurrence",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end",
            field=models.DateTimeField(db_index=True, verbose_name="end"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start",
            field=models.DateTimeField(db_index=True, verbose_name="start"),
        ),
        migrations.DeleteModel(
            name="Occurrence",
        ),
    ]
