# Generated by Django 3.2.4 on 2023-10-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0026_remove_llmsetting_llm_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmsetting',
            name='course',
        ),
        migrations.RemoveField(
            model_name='llmsetting',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='llmsetting',
            name='temperature',
        ),
    ]
