# Generated by Django 3.2.4 on 2023-10-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0027_auto_20231028_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmsetting',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='ohq.course'),
        ),
        migrations.AddField(
            model_name='llmsetting',
            name='llm_prompt',
            field=models.TextField(default=' \n        \\PINECONE CONTEXT\\\n        llm prompt \n        '),
        ),
        migrations.AddField(
            model_name='llmsetting',
            name='model_name',
            field=models.CharField(default='gpt-3.5-turbo-16k', max_length=30),
        ),
        migrations.AddField(
            model_name='llmsetting',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=5),
        ),
    ]
