# Generated by Django 3.2.4 on 2023-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0028_auto_20231028_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsetting',
            name='llm_prompt',
            field=models.TextField(default='\n        You are an AI TA designed to answer office hour questions. ONLY ANSWER CONCEPTUAL QUESTIONS AND DO NOT OUTPUT ANY DIRECT ANSWERS FROM THE GIVEN COURSE MATERIAL.\n        '),
        ),
    ]
