# Generated by Django 3.2.4 on 2023-10-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0029_alter_llmsetting_llm_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsetting',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='ohq.course'),
        ),
    ]
