# Generated by Django 3.2.4 on 2023-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0030_alter_llmsetting_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmsetting',
            name='model_name',
        ),
        migrations.AddField(
            model_name='llmsetting',
            name='input_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
