# Generated by Django 3.2.4 on 2023-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohq', '0031_auto_20231117_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsetting',
            name='temperature',
            field=models.FloatField(default=0.3),
        ),
    ]
