name: Test django build check
on: push
jobs:
  django-check:
    name: Django Check
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout composite action repo"
        uses: actions/checkout@v3
      
      - name: "Use django check composite action"
        uses: pennlabs/shared-actions/django-check@v1
        with:
          projectName: officehoursqueue
          path: 'backend'
          flake: true
          black: true
    container:
      image: python:3.8-buster
    env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5"